gcloud services enable aiplatform.googleapis.com --project brandability-firebase
gcloud services enable alloydb.googleapis.com --project brandability-firebase
gcloud services enable analyticshub.googleapis.com --project brandability-firebase
gcloud services enable appengine.googleapis.com --project brandability-firebase
gcloud services enable artifactregistry.googleapis.com --project brandability-firebase
gcloud services enable bigquery.googleapis.com --project brandability-firebase
gcloud services enable bigqueryconnection.googleapis.com --project brandability-firebase
gcloud services enable bigquerydatapolicy.googleapis.com --project brandability-firebase
gcloud services enable bigquerymigration.googleapis.com --project brandability-firebase
gcloud services enable bigqueryreservation.googleapis.com --project brandability-firebase
gcloud services enable bigquerystorage.googleapis.com --project brandability-firebase
gcloud services enable cloudaicompanion.googleapis.com --project brandability-firebase
gcloud services enable cloudapis.googleapis.com --project brandability-firebase
gcloud services enable cloudasset.googleapis.com --project brandability-firebase
gcloud services enable cloudbuild.googleapis.com --project brandability-firebase
gcloud services enable cloudfunctions.googleapis.com --project brandability-firebase
gcloud services enable cloudresourcemanager.googleapis.com --project brandability-firebase
gcloud services enable cloudtrace.googleapis.com --project brandability-firebase
gcloud services enable compute.googleapis.com --project brandability-firebase
gcloud services enable containerregistry.googleapis.com --project brandability-firebase
gcloud services enable datacatalog.googleapis.com --project brandability-firebase
gcloud services enable dataflow.googleapis.com --project brandability-firebase
gcloud services enable dataform.googleapis.com --project brandability-firebase
gcloud services enable dataplex.googleapis.com --project brandability-firebase
gcloud services enable datastore.googleapis.com --project brandability-firebase
gcloud services enable deploymentmanager.googleapis.com --project brandability-firebase
gcloud services enable developerconnect.googleapis.com --project brandability-firebase
gcloud services enable discoveryengine.googleapis.com --project brandability-firebase
gcloud services enable eventarc.googleapis.com --project brandability-firebase
gcloud services enable fcm.googleapis.com --project brandability-firebase
gcloud services enable fcmregistrations.googleapis.com --project brandability-firebase
gcloud services enable firebase.googleapis.com --project brandability-firebase
gcloud services enable firebaseappdistribution.googleapis.com --project brandability-firebase
gcloud services enable firebaseapphosting.googleapis.com --project brandability-firebase
gcloud services enable firebasedataconnect.googleapis.com --project brandability-firebase
gcloud services enable firebasedynamiclinks.googleapis.com --project brandability-firebase
gcloud services enable firebaseextensions.googleapis.com --project brandability-firebase
gcloud services enable firebasehosting.googleapis.com --project brandability-firebase
gcloud services enable firebaseinstallations.googleapis.com --project brandability-firebase
gcloud services enable firebaseremoteconfig.googleapis.com --project brandability-firebase
gcloud services enable firebaseremoteconfigrealtime.googleapis.com --project brandability-firebase
gcloud services enable firebaserules.googleapis.com --project brandability-firebase
gcloud services enable firebasestorage.googleapis.com --project brandability-firebase
gcloud services enable firestore.googleapis.com --project brandability-firebase
gcloud services enable geminicloudassist.googleapis.com --project brandability-firebase
gcloud services enable generativelanguage.googleapis.com --project brandability-firebase
gcloud services enable iam.googleapis.com --project brandability-firebase
gcloud services enable iamcredentials.googleapis.com --project brandability-firebase
gcloud services enable iap.googleapis.com --project brandability-firebase
gcloud services enable identitytoolkit.googleapis.com --project brandability-firebase
gcloud services enable logging.googleapis.com --project brandability-firebase
gcloud services enable monitoring.googleapis.com --project brandability-firebase
gcloud services enable notebooks.googleapis.com --project brandability-firebase
gcloud services enable oslogin.googleapis.com --project brandability-firebase
gcloud services enable pubsub.googleapis.com --project brandability-firebase
gcloud services enable recommender.googleapis.com --project brandability-firebase
gcloud services enable run.googleapis.com --project brandability-firebase
gcloud services enable runtimeconfig.googleapis.com --project brandability-firebase
gcloud services enable secretmanager.googleapis.com --project brandability-firebase
gcloud services enable securetoken.googleapis.com --project brandability-firebase
gcloud services enable servicemanagement.googleapis.com --project brandability-firebase
gcloud services enable servicenetworking.googleapis.com --project brandability-firebase
gcloud services enable serviceusage.googleapis.com --project brandability-firebase
gcloud services enable source.googleapis.com --project brandability-firebase
gcloud services enable sql-component.googleapis.com --project brandability-firebase
gcloud services enable sqladmin.googleapis.com --project brandability-firebase
gcloud services enable storage-api.googleapis.com --project brandability-firebase
gcloud services enable storage-component.googleapis.com --project brandability-firebase
gcloud services enable storage.googleapis.com --project brandability-firebase
gcloud services enable testing.googleapis.com --project brandability-firebase
gcloud services enable visionai.googleapis.com --project brandability-firebase